### ISSUE TITLE
Avoid transpose

### ISSUE THREAD

**Issue by BaptisteLefebvre** [spyking-circus/spyking-circus-ort#11]
We need to choose a format (i.e. `shape`) for our data buffer:

1. `(nb_channels, nb_samples)` currently used by all the blocks
2. `(nb_samples, nb_channels)` compatible with storage in a binary file on disk

Otherwise we will always have to transpose our data buffers many times. However, it requires that we modify all the existing blocks.

**Comment by yger** [comment]
This has been started in the transpose branch. I'll finish testing all blocks, then it will be merged and 2. will be the new default

**Comment by yger** [comment]
This has been done, and is now part of the merging branch, that will be added as soon as the OverlapStore object is finished
